### ISSUE TITLE
Bug: BetterEnumsSources.ENUM_EXTENSION_SOURCE_START has no using for Linq

### ISSUE THREAD

**Issue by Spoomer** [Ceiridge/BetterEnums#2]
I got an error in BetterEnumExtensions.cs in a project, which doesn't have the ImplicitUsing activated. It was an Error because of the Linq methods in GetEnumAttributes. The using for System.Linq is missing.

You can find the fix in the pull request https://github.com/Ceiridge/BetterEnums/pull/1

**Comment by Ceiridge** [comment]
Very good, thanks!
